# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this fSile is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Katarina Hoeger
email: katarina@katarinahoeger.com
description: >- # this means to ignore newlines until "baseurl:"
  Katarina Hoeger's personal website.
  A portfolio for independent work.
  A blog.
  Technical posts will generally feature some mixture of mathematics, computer science,
  music, or music technology.

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
linkedin_username: katarinahoeger
twitter_username: kfhoeger
github_username:  khoeger
soundcloud_username: katarina-hoeger
instagram_username: katarina_hoeger_art
siteowner: Katarina Hoeger
date_format: "%-d %B %Y"
short_date_format: "%-d %B"
time_format: "%I:%M %p"
future: true

# Build settings
markdown: kramdown
#theme: minima
plugins:
  - jekyll-feed
  # - jekyll-pdf-embed
permalink: /:year/:month/:day/:title
# Collections
collections:
  projects_list:
    output : true

  events_list:
    output : true
    #future : true

  posts:
    output : true
# Defaults
defaults:
  -
    scope:
      path: "" # an empty string means all files in the project
      type: "posts"
    values:
      # layout: "default"
      layout: "post"
  -
    scope:
      path: ""
      type: "events_list"
    values:
      #layout: "default"
      layout: "event"
  -
    scope:
      path: ""
      type: "projects_list"
    values:
      layout: project

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
